package platform

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// BundleFiles projects the reviewed local inputs without executing tools. The
// adoption signal is derived from Bootstrap identity and is excluded to avoid a
// fingerprint cycle. Its Kustomization entry remains part of the fingerprint.
func (p *Project) BundleFiles() (map[string][]byte, error) {
	paths := []string{inputDir + "/config.json", inputDir + "/versions.lock.json", inputDir + "/health/ready.lua", inputDir + "/values/cilium.json", inputDir + "/values/cert-manager.json", inputDir + "/values/envoy-gateway.json", inputDir + "/bootstrap/kind.json", inputDir + "/bootstrap/project.json", inputDir + "/bootstrap/root.json", inputDir + "/bootstrap/cilium-seed.yaml", inputDir + "/bootstrap/argocd-self-seed.yaml"}
	dirs := []string{p.Config.RootPath, "gitops/platform/applications/overlays/development", "gitops/platform/management/projects/overlays/development", "gitops/workloads/applications/overlays/development", "gitops/workloads/web-smoke/overlays/development"}
	for _, path := range p.Config.Components {
		dirs = append(dirs, path)
	}
	for _, dir := range dirs {
		path := dir + "/kustomization.yaml"
		paths = append(paths, path)
		var k struct {
			APIVersion string   `json:"apiVersion"`
			Kind       string   `json:"kind"`
			Resources  []string `json:"resources"`
		}
		if e := readJSON(filepath.Join(p.Root, path), &k); e != nil {
			return nil, e
		}
		for _, res := range k.Resources {
			if res == "" || filepath.Base(res) != res || strings.Contains(res, ":") {
				return nil, errors.New("bundle must use local manifest files")
			}
			if res != "signal.json" {
				paths = append(paths, dir+"/"+res)
			}
		}
	}
	files := map[string][]byte{}
	for _, path := range paths {
		b, e := os.ReadFile(filepath.Join(p.Root, path))
		if e != nil {
			return nil, e
		}
		files[path] = b
	}
	for _, name := range []string{"cilium", "argocd-self"} {
		if !bytes.Equal(files[inputDir+"/bootstrap/"+name+"-seed.yaml"], files[p.Config.Components[name]+"/rendered.yaml"]) {
			return nil, fmt.Errorf("%s Seed differs from GitOps payload", name)
		}
	}
	return files, nil
}

// DecodeJSONManifests accepts the JSON YAML stream generated by this package,
// including hand-authored Kubernetes Lists. It does not execute YAML tags.
func DecodeJSONManifests(data []byte) ([]Object, error) {
	var out []Object
	for _, part := range bytes.Split(data, []byte("\n---\n")) {
		if len(bytes.TrimSpace(part)) == 0 {
			continue
		}
		objs, e := decodeObjects(part)
		if e != nil {
			return nil, e
		}
		out = append(out, objs...)
	}
	return out, nil
}
func BundleDigest(files map[string][]byte) string {
	hashes := map[string]string{}
	for path, b := range files {
		hashes[path] = hash(b)
	}
	b, _ := json.Marshal(hashes)
	return hash(b)
}
func ImageList(images map[string]string) []string {
	unique := map[string]bool{}
	for _, im := range images {
		unique[im] = true
	}
	out := make([]string, 0, len(unique))
	for im := range unique {
		out = append(out, im)
	}
	sort.Strings(out)
	return out
}
