package installation

import (
	"atlas-refactor/internal/atlas"
	"atlas-refactor/internal/platform"
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const bootstrapDir = "platform/development/bootstrap/"
const appCatalog = "gitops/platform/applications/overlays/development/resources.json"
const projectCatalog = "gitops/platform/management/projects/overlays/development/resources.json"
const signalPath = "gitops/platform/management/argocd-self/overlays/development/signal.json"

type Files map[string][]byte

// Product is generated by the release builder, authenticated as part of the
// attested archive, and immutable during installation. It contains no checkout.
type Product struct {
	Schema       int        `json:"schema"`
	Version      string     `json:"version"`
	SourceCommit string     `json:"sourceCommit"`
	Lock         atlas.Lock `json:"lock"`
	Images       []string   `json:"images"`
	Assets       Files      `json:"assets"`
	Base         Files      `json:"base"`
	Full         Files      `json:"full"`
	Tools        []Tool     `json:"tools"`
}

func BuildProduct(root, version, source string, tools platform.Tools, locks []Tool) (Product, error) {
	p, e := platform.Load(root, tools)
	if e != nil {
		return Product{}, e
	}
	if e = p.VerifyArtifacts(); e != nil {
		return Product{}, e
	}
	if e = p.ValidateCapabilityActivation(); e != nil {
		return Product{}, e
	}
	all, e := p.BundleFiles()
	if e != nil {
		return Product{}, e
	}
	files := Files{}
	for path, b := range all {
		if strings.HasPrefix(path, "gitops/") && path != signalPath || path == bootstrapDir+"kind.json" || path == bootstrapDir+"root.json" || path == bootstrapDir+"project.json" || path == bootstrapDir+"cilium-seed.yaml" || path == bootstrapDir+"argocd-self-seed.yaml" {
			files[path] = b
		}
	}
	// Author ciphertext never crosses the product boundary, including dormant
	// manifests. The installer inserts exactly three newly sealed objects later.
	files[CredentialPath] = JSON(platform.Object{"apiVersion": "v1", "kind": "List", "items": []any{}})
	base := Files{}
	for path, b := range files {
		base[path] = b
	}
	names, e := p.ResolveCapabilities([]string{"secrets-controller"})
	if e != nil {
		return Product{}, e
	}
	activation, e := p.CapabilityActivation(names)
	if e != nil {
		return Product{}, e
	}
	for path, b := range activation {
		base[path] = b
	}
	var l atlas.Lock
	b, e := os.ReadFile(filepath.Join(root, "versions.lock.json"))
	if e != nil {
		return Product{}, e
	}
	if e = Decode(b, &l); e != nil {
		return Product{}, e
	}
	assets := Files{}
	for _, path := range []string{l.Chart, "assets/argocd-values.yaml", "assets/argocd-cm.yaml"} {
		b, e = os.ReadFile(filepath.Join(root, path))
		if e != nil {
			return Product{}, e
		}
		assets[path] = b
	}
	out := Product{Schema: 1, Version: version, SourceCommit: source, Lock: l, Images: platform.ImageList(p.Lock.Images), Assets: assets, Base: base, Full: files, Tools: locks}
	return out, out.Validate()
}
func (p Product) Validate() error {
	if p.Schema != 1 || !commit.MatchString(p.SourceCommit) || !regexpVersion(p.Version) {
		return errors.New("invalid product identity")
	}
	if e := p.Lock.Validate(); e != nil {
		return e
	}
	if len(p.Assets) != 3 || Digest(p.Assets[p.Lock.Chart]) != p.Lock.ChartSHA256 {
		return errors.New("invalid product assets")
	}
	for path, h := range p.Lock.Assets {
		if Digest(p.Assets[path]) != h {
			return fmt.Errorf("invalid product asset: %s", path)
		}
	}
	if len(p.Images) < 10 {
		return errors.New("incomplete image inventory")
	}
	for i, image := range p.Images {
		_, d, ok := strings.Cut(image, "@sha256:")
		if !ok || !sha.MatchString(d) || i > 0 && image <= p.Images[i-1] {
			return errors.New("invalid or unsorted image inventory")
		}
	}
	if e := ValidateTools(p.Tools); e != nil {
		return e
	}
	for _, files := range []Files{p.Base, p.Full} {
		if e := atlas.ValidateInstallationKind(files[bootstrapDir+"kind.json"], 8080, 8443); e != nil {
			return e
		}
		for _, path := range []string{appCatalog, projectCatalog, RootPath + "/resources.json", CredentialPath, bootstrapDir + "root.json", bootstrapDir + "project.json", bootstrapDir + "kind.json"} {
			if len(files[path]) == 0 {
				return fmt.Errorf("missing runtime template: %s", path)
			}
		}
		for path, b := range files {
			if filepath.Clean(path) != path || strings.Contains(path, "..") || !(strings.HasPrefix(path, "gitops/") || strings.HasPrefix(path, bootstrapDir)) || path == signalPath {
				return fmt.Errorf("invalid runtime path: %s", path)
			}
			if strings.HasSuffix(path, "kustomization.yaml") {
				var k struct {
					APIVersion, Kind string
					Resources        []string
				}
				if e := Decode(b, &k); e != nil {
					return e
				}
				if k.Kind != "Kustomization" || len(k.Resources) == 0 {
					return errors.New("invalid Kustomization")
				}
				for _, r := range k.Resources {
					if r == "" || filepath.Base(r) != r || strings.ContainsAny(r, ":\\") {
						return errors.New("nonlocal Kustomize input")
					}
					ref := filepath.Join(filepath.Dir(path), r)
					if ref != signalPath && len(files[ref]) == 0 {
						return fmt.Errorf("missing Kustomize input %s", ref)
					}
				}
				continue
			}
			objects, e := platform.DecodeJSONManifests(b)
			if e != nil {
				return fmt.Errorf("runtime template %s: %w", path, e)
			}
			for _, o := range objects {
				if o["kind"] == "Secret" || o["kind"] == "SealedSecret" {
					return errors.New("product must not carry credentials or author ciphertext")
				}
			}
		}
		for _, pair := range [][2]string{{"cilium", "gitops/platform/networking/cilium/overlays/development/rendered.yaml"}, {"argocd-self", "gitops/platform/management/argocd-self/overlays/development/rendered.yaml"}} {
			if len(files[bootstrapDir+pair[0]+"-seed.yaml"]) == 0 || !bytes.Equal(files[bootstrapDir+pair[0]+"-seed.yaml"], files[pair[1]]) {
				return errors.New("Seed and GitOps payload differ")
			}
		}
	}
	for path, b := range p.Base {
		if path != appCatalog && path != projectCatalog && !bytes.Equal(b, p.Full[path]) {
			return fmt.Errorf("two-phase template changed Bootstrap input: %s", path)
		}
	}
	return nil
}
func regexpVersion(v string) bool {
	return len(v) > 1 && len(v) < 65 && v[0] == 'v' && strings.IndexFunc(v, func(r rune) bool { return !(r >= 'a' && r <= 'z' || r >= '0' && r <= '9' || r == '.' || r == '-') }) < 0
}

// Project modifies data leaves, never text-substitutes executable configuration.
// The complete release file inventory and its authority graph remain fixed.
func (p Product) Project(c Config, full bool) (Files, error) {
	if e := c.Validate(); e != nil {
		return nil, e
	}
	if e := p.Validate(); e != nil {
		return nil, e
	}
	template := p.Base
	if full {
		template = p.Full
	}
	out := Files{}
	var replace func(any) any
	replace = func(v any) any {
		switch x := v.(type) {
		case string:
			if x == SourceRepository {
				return c.Repository
			}
			if x == SourceRevision {
				return c.Branch
			}
		case map[string]any:
			for k, v := range x {
				x[k] = replace(v)
			}
		case []any:
			for i, v := range x {
				x[i] = replace(v)
			}
		}
		return v
	}
	for path, b := range template {
		parts := bytes.Split(b, []byte("\n---\n"))
		rendered := [][]byte{}
		for _, part := range parts {
			if len(bytes.TrimSpace(part)) == 0 {
				continue
			}
			var obj any
			if e := Decode(part, &obj); e != nil {
				return nil, e
			}
			obj = replace(obj)
			if strings.HasPrefix(path, "gitops/") {
				setRedirectPort(obj, c.HTTPSPort)
			}
			if path == bootstrapDir+"kind.json" {
				m := obj.(map[string]any)
				nodes, ok := m["nodes"].([]any)
				if !ok || len(nodes) != 4 {
					return nil, errors.New("product must have four nodes")
				}
				ports := nodes[1].(map[string]any)["extraPortMappings"].([]any)
				ports[0].(map[string]any)["hostPort"] = c.HTTPPort
				ports[1].(map[string]any)["hostPort"] = c.HTTPSPort
			}
			rendered = append(rendered, bytes.TrimSuffix(JSON(obj), []byte("\n")))
		}
		out[path] = append(bytes.Join(rendered, []byte("\n---\n")), '\n')
	}
	return out, nil
}
func sortedFiles(f Files) []string {
	out := make([]string, 0, len(f))
	for p := range f {
		out = append(out, p)
	}
	sort.Strings(out)
	return out
}

// The HTTPRoute redirect must agree with the selected host TLS port.
func setRedirectPort(v any, port int) {
	switch x := v.(type) {
	case map[string]any:
		for k, v := range x {
			if k == "requestRedirect" {
				if m, ok := v.(map[string]any); ok {
					if m["scheme"] == "https" {
						m["port"] = port
					}
				}
			} else {
				setRedirectPort(v, port)
			}
		}
	case []any:
		for _, v := range x {
			setRedirectPort(v, port)
		}
	}
}
